# Site settings
title: My Recipe Collection
description: A collection of recipes for real, actually-edible food.
theme: minima

# GitHub Pages settings
# The baseurl is the subpath of your site, e.g. /recipes
# The url is the main domain.
# Replace "averykhoo" with your GitHub username.
# Replace "recipes" with your repository name.
baseurl: "/recipes"
url: "https://averykhoo.github.io"

# Enable GitHub Flavored Markdown
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

# Configure collections for each recipe folder
collections:
  curated-untested:
    output: true
  in-progress:
    output: true
  recipes:
    output: true

# Apply the default theme layout to all documents in the site
defaults:
  - scope:
      path: ""
    values:
      layout: "default"