# Use the jekyll-remote-theme plugin
plugins:
  - jekyll-remote-theme

# Set the remote theme to Just the Docs
remote_theme: just-the-docs/just-the-docs

# Site settings
title: 🎂📖
description: A collection of recipes for real, actually-edible food.

# Enable the theme's built-in search
search_enabled: true

# --- Jekyll Collections Configuration ---
# 1. Define the collections for Jekyll to process
collections:
  curated-untested:
    output: true
  in-progress:
    output: true
  recipes:
    output: true

# 2. Configure how Just the Docs displays the collections in the navigation
just_the_docs:
  collections:
    recipes:
      name: Recipes
    in-progress:
      name: In Progress
    curated-untested:
      name: Curated & Un-tested

# Apply the default theme layout to all documents
defaults:
  - scope:
      path: ""
    values:
      layout: "default"