plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

# Set the remote theme to Just the Docs
remote_theme: just-the-docs/just-the-docs

# Site settings
title: Recipes
description: A collection of recipes for real, actually-edible food.

# Enable the theme's built-in search
search_enabled: true

# --- Jekyll Collections Configuration ---
# 1. Define the collections for Jekyll to process
collections:
  curated-untested:
    output: true
  in-progress:
    output: true
  recipes:
    output: true

# 2. Configure how Just the Docs displays the collections in the navigation
just_the_docs:
  collections:
    recipes:
      name: Recipes
      nav_fold: true
    in-progress:
      name: In Progress
      nav_fold: true
    curated-untested:
      name: Curated & Un-tested
      nav_fold: true

# Apply the default theme layout to all documents
defaults:
  - scope:
      path: ""
    values:
      layout: "default"

# Add a floating search button on pages for easy access
search:
  button: true
  # Add a keyboard shortcut (Ctrl+K or Cmd+K) to focus the search bar
  focus_shortcut_key: "k"

# Add a "Back to top" link at the bottom of long recipe pages
back_to_top: true
back_to_top_text: "Back to top"

# Enable the copy button on code snippets (useful for ingredient lists formatted in blocks)
enable_copy_code_button: true

# Add a link to your GitHub repo in the top right corner
aux_links:
  "View on GitHub":
    - "https://github.com/averykhoo/recipes" # Replace with your repo URL if different

# Set a path/url to a favicon that will be displayed by the browser
favicon_ico: "favicon.ico"

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "11.12.0"

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "View on GitHub."
gh_edit_repository: "https://github.com/averykhoo/recipes" # the github URL for your repo
gh_edit_branch: "master" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately