name: Deploy Recipes to GitHub Pages

on:
  push:
    branches:
      - master # Or 'main', depending on your repository's default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Assemble docs directory
        run: |
          mkdir docs
          cp -r curated-untested in-progress menus recipes docs/
          cp README.md docs/index.md
          # Copy any other top-level markdown files you want on the site
          cp TODO.md TODO-SAUCES.md more-christmas-possibilities.md docs/

      - name: Build site with MkDocs
        run: mkdocs build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site